apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mood-portal
  description: Mood portal
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=mood-portal'
spec:
  type: service
  lifecycle: integration
  owner: hope-dev-team1
  system: devx-mood
  consumesApis:
    - mood-sensors-apis
