apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mood-portal
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: mood-portal
spec:
  source:
    git:
      url: https://github.com/Tembhum/mood-portal
      ref:
        branch: dev
  env:
    - name: SENSORS_ACTIVATE_API
      value: http://mysensors.default.h2o-4-1550.h2o.vmware.com/activate
    - name: SENSORS_MEASURE_API
      value: http://mysensors.default.h2o-4-1550.h2o.vmware.com/measure
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"