apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: myportal-info
  description: A catalog for mood-portal microservice
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/myportal.yaml